require linux-mainline.inc

DESCRIPTION = "Mainline Longterm Linux kernel"

LIC_FILES_CHKSUM = "file://COPYING;md5=6bc538ed5bd9a7fc9398086aedcd7e46"

SRC_URI[sha256sum] = "a9b99fb376f9fcd699c7c252aeef3bb5ba26280eb049711ac091b2eb2b487c03"

LINUX_VERSION = "6.7.10"

SRC_URI:append:orange-pi-zero3  = " \
    file://defconfig \
    file://0001-arm64-dts-sun50i-h616-orangepi-zero2-Enable-GPU-mali.patch \
    file://0002-arm64-dts-allwinner-h616-Add-thermal-sensor-and-ther.patch \
    file://0003-arm64-dts-allwinner-sun50i-h616-Add-GPU-node.patch \
    file://0004-arm64-dts-allwinner-sun50i-h616-Add-VPU-node.patch \
    file://0005-arm64-dts-h616-add-hdmi-support-for-zero2-and-zero3.patch \
    file://0006-arm64-dts-allwinner-h616-Add-device-node-for-SID.patch \
    file://0007-arm64-dts-allwinner-h616-Add-efuse_xlate-cpu-frequen.patch \
    file://0008-arm64-dts-sun50i-h618-orangepi-zero3-Enable-GPU-mali.patch \
    file://0009-Patching-kernel-sunxi64-files-arch-arm64-boot-dts-al.patch \
    file://0010-arm64-dts-allwiner-sun50i-h616.dtsi-add-usb-ehci-ohc.patch \
    file://0011-ASoC-hdmi-codec-fix-channel-allocation.patch \
    file://0012-ASoC-AC200-Initial-driver.patch \
    file://0013-arm64-dts-sun50i-h616-orangepi-zero2-reg_usb1_vbus-s.patch \
    file://0014-arm64-dts-h616-add-wifi-support-for-orange-pi-zero-2.patch \
    file://0015-arm64-dts-allwinner-h616-orangepi-zero2-Enable-expan.patch \
    file://0016-arm64-dts-allwinner-overlay-Add-Overlays-for-sunxi64.patch \
    file://0017-arm64-dts-allwinner-h616-Fix-thermal-zones-add-missi.patch \
    file://0018-add-nodes-for-sunxi-info-sunxi-addr-and-sunxi-dump-r.patch \
    file://0019-drm-sun4i-de2-de3-Change-CSC-argument.patch \
    file://0020-drm-sun4i-de2-de3-Merge-CSC-functions-into-one.patch \
    file://0021-drm-sun4i-de2-de3-call-csc-setup-also-for-UI-layer.patch \
    file://0022-drm-sun4i-dw-hdmi-Deinit-PHY-in-fail-path.patch \
    file://0023-drm-sun4i-dw-hdmi-Remove-double-encoder-cleanup.patch \
    file://0024-drm-sun4i-dw-hdmi-Switch-to-bridge-functions.patch \
    file://0025-drm-sun4i-dw-hdmi-Make-sun8i_hdmi_phy_get-more-intui.patch \
    file://0026-drm-sun4i-dw-hdmi-check-for-phy-device-first.patch \
    file://0027-WIP-drm-sun4i-de3-Add-support-for-YUV420-output.patch \
    file://0028-drv-gpu-drm-sun4i-Add-GEM-allocator.patch \
    file://0029-drm-sun4i-de3-Implement-AFBC-support.patch \
    file://0030-wip-fix-H6-4k-60.patch \
    file://0031-drv-gpu-drm-gem-dma-Export-with-handle-allocator.patch \
    file://0032-drm-sun4i-de2-Initialize-layer-fields-earlier.patch \
    file://0033-drm-bridge-dw-hdmi-add-mtmdsclock-parameter-to-phy-c.patch \
    file://0034-drm-sun4i-mixer-Add-caching-support.patch \
    file://0035-Code-by-Jernej-Skrabec-jernej.skrabec-gmail.com.patch \
    file://0036-drm-sun4i-Don-t-show-error-for-deferred-probes.patch \
    file://0037-.patch \
    file://0038-drv-gpu-drm-sun4i-Add-HDMI-audio-sun4i-hdmi-encoder.patch \
    file://0039-code-based-on-orangepi-xunlong-258384131-qq.com.patch \
    file://0040-drv-soc-sunxi-sram-Add-SRAM-C1-H616-handling.patch \
    file://0041-Code-based-on-orangepi-xunlong-258384131-qq.com.patch \
    file://0042-This-hack-stops-kernel-oops-at-alsa-cards-caps-query.patch \
    file://0043-WIP-I2S-multi-channel.patch \
    file://0044-arm64-xor-Select-32regs-without-benchmark-to-speed-u.patch \
    file://0045-ASoC-sun8i-codec-Enable-bus-clock-at-STANDBY-and-hig.patch \
    file://0046-ASoC-sun8i-codec-Implement-jack-and-accessory-detect.patch \
    file://0047-sound-soc-sun8i-codec-Add-support-for-digital-part-o.patch \
    file://0048-ASoC-sun50i-codec-analog-Add-support-for-internal-bi.patch \
    file://0049-ASoC-sun50i-codec-analog-Move-suspend-resume-to-set_.patch \
    file://0050-ASoC-sun50i-codec-analog-Enable-jack-detection-on-st.patch \
    file://0051-ASoC-sunxi-sun8i-codec-Improve-jack-button-handling-.patch \
    file://0052-sound-soc-sun8i-codec-Drop-debug-statements.patch \
    file://0053-sound-soc-sunxi-sun8i-codec-analog-enable-sound.patch \
    file://0054-ASOC-sun9i-hdmi-audio-Initial-implementation.patch \
    file://0055-sound-soc-ac100-codec-Support-analog-part-of-X-Power.patch \
    file://0056-sound-soc-sunxi-Provoke-the-early-load-of-sun8i-code.patch \
    file://0057-sound-soc-sunxi-sun4i-spdif-add-mclk_multiplier.patch \
    file://0058-sound-soc-sunxi-sun4i-codec-adcis-select-capture-sou.patch \
    file://0059-drv-pinctrl-sunxi-pinctrl-sun50i-h6.c-GPIO-disable_s.patch \
    file://0060-pinctrl-pinmux-Hide-temporary-probe-deferal-error.patch \
    file://0061-drv-pinctrl-pinctrl-sun50i-a64-disable_strict_mode.patch \
    file://0062-cpufreq-sun50i-Show-detected-CPU-bin-for-easier-debu.patch \
    file://0063-ASoC-ec25-New-codec-driver-for-the-EC25-modem.patch \
    file://0064-sound-soc-ac100-Make-sure-we-shutdown-the-audio-outp.patch \
    file://0065-nvmem-sunxi_sid-add-sunxi_get_soc_chipid-sunxi_get_s.patch \
    file://0066-drv-nvmem-sunxi_sid-Support-SID-on-H616.patch \
    file://0067-dma-sun6i-dma-add-h616-support.patch \
    file://0068-opp-core-Avoid-confusing-error-when-no-regulator-is-.patch \
    file://0069-sunxi-Use-dev_err_probe-to-handle-EPROBE_DEFER-error.patch \
    file://0070-mtd-spi-nor-Add-regulator-support.patch \
    file://0071-drv-mtd-nand-raw-nand_ids.c-add-H27UBG8T2BTR-BC-nand.patch \
    file://0072-drv-clocksource-arm_arch_timer-fix-a64-timejump.patch \
    file://0073-power-supply-axp20x_battery-Add-support-for-reportin.patch \
    file://0074-drivers-iommu-sun50i-iommu-fix-iommu-on-h616.patch \
    file://0075-iommu-sun50i-Allow-page-sizes-multiple-of-4096.patch \
    file://0076-regulator-axp20x-Enable-over-temperature-protection-.patch \
    file://0077-regulator-axp20x-Add-support-for-vin-supply-for-driv.patch \
    file://0078-regulator-axp20x-Turn-N_VBUSEN-to-input-on-x-powers-.patch \
    file://0079-regulator-Add-simple-driver-for-enabling-a-regulator.patch \
    file://0080-regulator-tp65185x-Add-tp65185x-eInk-panel-regulator.patch \
    file://0081-clk-sunxi-ng-add-support-for-rate-resetting-notifier.patch \
    file://0082-drv-clk-sunxi-ng-ccu-add-min-max-rate-sun50i-a64.patch \
    file://0083-clk-sunxi-ng-a64-Increase-PLL_AUDIO-base-frequency.patch \
    file://0084-clk-sunxi-ng-a64-keep-tcon0-clock-rate-when-pll-vide.patch \
    file://0085-HACK-clk-sunxi-ng-unify-parent-for-HDMI-clocks.patch \
    file://0086-clk-sunxi-ng-h6-Reparent-CPUX-during-PLL-CPUX-rate-c.patch \
    file://0087-clk-sunxi-ng-ccu-sun6i-rtc-fix-32k-clk.patch \
    file://0088-clk-sunxi-ng-Export-CLK_DRAM-for-devfreq.patch \
    file://0089-clk-sunxi-ng-Set-maximum-P-and-M-factors-to-1-for-H3.patch \
    file://0090-clk-sunxi-ng-Don-t-use-CPU-PLL-gating-and-CPUX-repar.patch \
    file://0091-clk-Implement-protected-clocks-for-all-OF-clock-prov.patch \
    file://0092-clk-gate-add-support-for-regmap-based-gates.patch \
    file://0093-drivers-devfreq-sun8i-a33-mbus-disable-autorefresh.patch \
    file://0094-regulator-tp65185-Add-hwmon-device-for-reading-tempe.patch \
    file://0095-drv-rtc-sun6i-Add-Allwinner-H616-support.patch \
    file://0096-drv-rtc-sun6i-support-RTCs-without-external-LOSCs.patch \
    file://0097-rtc-sun6i-Allow-RTC-wakeup-after-shutdown.patch \
    file://0098-Revert-clk-qcom-Support-protected-clocks-property.patch \
    file://0099-Add-dump_reg-and-sunxi-sysinfo-drivers.patch \
    file://0100-Revert-drm-sun4i-lvds-Invert-the-LVDS-polarity.patch \
    file://0101-WIP-dw-hdmi-cec-sleep-100ms-on-error.patch \
    file://0102-drm-bridge-dw-hdmi-Allow-to-accept-HPD-status-from-o.patch \
    file://0103-drm-bridge-dw-hdmi-support-configuring-phy-for-deep-.patch \
    file://0104-drm-bridge-dw-hdmi-Report-HDMI-hotplug-events.patch \
    file://0105-drv-thermal-sun8i_thermal-Add-for-H616.patch \
    file://0106-thermal-sun8i-Be-loud-when-probe-fails.patch \
    file://0107-power-supply-ip5xxx-Report-remaining-battery-capacit.patch \
    file://0108-power-supply-ip5xxx-Modify-initial-configuration.patch \
    file://0109-power-supply-ip5xxx-Add-boost-status-property.patch \
    file://0110-power-supply-ip5xxx-Add-ip5xxx-usb-supply.patch \
    file://0111-power-supply-ip5xxx-Add-support-for-POWER_SUPPLY_PRO.patch \
    file://0112-power-supply-ip5xxx-Add-support-for-POWER_SUPPLY_PRO.patch \
    file://0113-power-supply-Add-support-for-USB_BC_ENABLED-and-USB_.patch \
    file://0114-power-supply-axp20x-usb-power-Support-input-current-.patch \
    file://0115-power-supply-axp20x-usb-power-Change-Vbus-hold-volta.patch \
    file://0116-power-supply-axp20x_battery-Fix-charging-done-detect.patch \
    file://0117-power-supply-axp20x-battery-Support-POWER_SUPPLY_PRO.patch \
    file://0118-power-supply-axp20x_battery-Setup-thermal-regulation.patch \
    file://0119-power-supply-axp20x_battery-Send-uevents-for-status-.patch \
    file://0120-power-supply-axp20x_battery-Monitor-battery-health.patch \
    file://0121-power-supply-axp20x-battery-Add-support-for-POWER_SU.patch \
    file://0122-power-supply-axp20x-battery-Enable-poweron-by-RTC-al.patch \
    file://0123-power-axp20x_battery-Allow-to-set-target-voltage-to-.patch \
    file://0124-mfd-axp20x-Add-battery-IRQ-resources.patch \
    file://0125-power-axp803-Add-interrupts-for-low-battery-power-co.patch \
    file://0126-drv-mfd-axp20x-add-sysfs-interface.patch \
    file://0127-leds-axp20x-Support-charger-LED-on-AXP20x-like-PMICs.patch \
    file://0128-mfd-Add-support-for-X-Powers-AC200.patch \
    file://0129-iio-adc-sun4i-gpadc-iio-Allow-to-use-sun5i-a13-gpadc.patch \
    file://0130-i2c-mv64xxx-Don-t-make-a-fuss-when-pinctrl-recovery-.patch \
    file://0131-iio-adc-axp20x_adc-allow-to-set-TS-pin-to-GPADC-mode.patch \
    file://0132-drv-iio-adc-axp20x_adc-arm64-dts-axp803-hwmon-enable.patch \
    file://0133-drv-iio-adc-Kconfig-enable-A80-A64-H5-for-THS.patch \
    file://0134-drv-iio-adc-sun4i-gpadc-iio-rename-A33-specified-reg.patch \
    file://0135-drv-iio-adc-sun4i-gpadc-iio-sampling-start-end-code-.patch \
    file://0136-drv-iio-adc-sun4i-gpadc-iio-support-clocks-and-reset.patch \
    file://0137-drv-iio-adc-sun4i-gpadc-iio-multible-sensors-support.patch \
    file://0138-drv-iio-adc-sun4i-gpadc-iio-support-nvmem-calibratio.patch \
    file://0139-drv-iio-adc-sun4i-gpadc-iio-add-interrupt-support.patch \
    file://0140-drv-iio-adc-sun4i-gpadc-iio-add-H3-thermal-sensor.patch \
    file://0141-drv-iio-adc-sun4i-gpadc-iio-add-A83T-thermal-sensor.patch \
    file://0142-drv-iio-adc-sun4i-gpadc-iio-add-A80-thermal-sensor.patch \
    file://0143-drv-iio-adc-sun4i-gpadc-iio-add-A64-thermal-sensor.patch \
    file://0144-drv-iio-sun4i-gpadc-iio-don-t-force-poweroff.patch \
    file://0145-iio-st_sensors-Don-t-report-error-when-the-device-is.patch \
    file://0146-drv-spi-spi-sun4i.c-spi-bug-low-on-sck.patch \
    file://0147-WIP-drm-panfrost-add-support-for-custom-soft-reset-o.patch \
    file://0148-drm-lima-dvfs-switch-gov-to-performance.patch \
    file://0149-drv-staging-media-sunxi-cedrus-add-H616-variant.patch \
    file://0150-media-cedrus-Increase-H6-clock-rate.patch \
    file://0151-media-cedrus-Fix-failure-to-clean-up-hardware-on-pro.patch \
    file://0152-media-cedrus-Implement-AFBC-YUV420-formats-for-H265.patch \
    file://0153-media-cedrus-h265-Fix-configuring-bitstream-size.patch \
    file://0154-media-cedrus-add-format-filtering-based-on-depth-and.patch \
    file://0155-media-cedrus-Don-t-CPU-map-source-buffers.patch \
    file://0156-media-Add-NV12-and-P010-AFBC-compressed-formats.patch \
    file://0157-net-stmmac-sun8i-Use-devm_regulator_get-for-PHY-regu.patch \
    file://0158-net-stmmac-sun8i-Rename-PHY-regulator-variable-to-re.patch \
    file://0159-net-stmmac-sun8i-Add-support-for-enabling-a-regulato.patch \
    file://0160-drv-net-stmmac-dwmac-sun8i-second-EMAC-clock-registe.patch \
    file://0161-net-phy-Add-support-for-AC200-EPHY.patch \
    file://0162-mmc-add-delay-after-power-class-selection.patch \
    file://0163-mmc-sunxi-mmc-Remove-runtime-PM.patch \
    file://0164-drv-mmc-host-sunxi-mmc-add-h5-emmc-compatible.patch \
    file://0165-drv-mmc-host-sunxi-mmc-Disable-DDR52-mode-on-all-A20.patch \
    file://0166-mmc-host-sunxi-mmc-Fix-H6-emmc.patch \
    file://0167-Input-axp20x-pek-allow-wakeup-after-shutdown.patch \
    file://0168-wip-H6-deinterlace.patch \
    file://0169-media-sun6i-csi-capture-Use-subdev-operation-to-acce.patch \
    file://0170-media-sun6i-csi-subdev-Use-subdev-active-state-to-st.patch \
    file://0171-media-sun6i-csi-Add-multicamera-support-for-parallel.patch \
    file://0172-media-sun6i-csi-merge-sun6i_csi_formats-and-sun6i_cs.patch \
    file://0173-wip-media-sunxi-sun8i-di-fix-race-condition.patch \
    file://0174-media-sun6i-csi-add-V4L2_CAP_IO_MC-capability.patch \
    file://0175-media-sun6i-csi-implement-vidioc_enum_framesizes.patch \
    file://0176-mfd-sun4i-gpadc-Interrupt-numbers-should-start-from-.patch \
    file://0177-Fix-intptr_t-typedef.patch \
    file://0178-include-uapi-drm_fourcc-add-ARM-tiled-format-modifie.patch \
    file://0179-dt-bindings-axp20x-adc-allow-to-use-TS-pin-as-GPADC.patch \
    file://0180-dt-bindings-input-gpio-vibrator-Don-t-require-enable.patch \
    file://0181-bus-sunxi-rsb-Always-check-register-address-validity.patch \
    file://0182-firmware-arm_scpi-Support-unidirectional-mailbox-cha.patch \
    file://0183-firmware-scpi-Add-support-for-sending-a-SCPI_CMD_SET.patch \
    file://0184-gnss-ubx-Send-soft-powerdown-message-on-suspend.patch \
    file://0185-mailbox-Allow-to-run-mailbox-while-timekeeping-is-su.patch \
    file://0186-drv-media-dvb-frontends-si2168-fix-cmd-timeout.patch \
    file://0187-input-pinephone-keyboard-Allow-disabling-the-keyboar.patch \
    file://0188-input-pinephone-keyboard-Allow-to-disable-Fn-layer-p.patch \
    file://0189-input-pinephone-keyboard-Don-t-print-error-when-the-.patch \
    file://0190-input-pinephone-keyboard-Wait-a-bit-after-enabling-v.patch \
    file://0191-input-gpio-vibra-Allow-to-use-vcc-supply-alone-to-co.patch \
    file://0192-drv-gpu-drm-panel-simple-Add-compability-olinuxino-l.patch \
    file://0193-drm-panel-st7703-Fix-xbd599-timings-to-make-refresh-.patch \
    file://0194-usb-quirks-Add-USB_QUIRK_RESET-for-Quectel-EG25G-Mod.patch \
    file://0195-Mark-some-slow-drivers-for-async-probe-with-PROBE_PR.patch \
    file://0196-iio-stk3310-Implement-vdd-supply-and-power-it-off-du.patch \
    file://0197-iio-light-stk3310-Add-support-for-I2C-regulator.patch \
    file://0198-iio-core-Add-option-to-force-identity-mount-matrix.patch \
    file://0199-iio-magnetometer-add-a-driver-for-Voltafield-AF8133J.patch \
    file://0200-iio-af8133j-Cleanup-probe-and-power-up-down.patch \
    file://0201-iio-af8133j-Add-runtime-power-management.patch \
    file://0202-iio-af8133j-Add-support-for-buffer.patch \
    file://0203-iio-af8133j-Avoid-compiler-warning.patch \
    file://0204-Fix-warning-multi-line-comment.patch \
    file://0205-usb-gadget-Fix-dangling-pointer-in-netdev-private-da.patch \
    file://0206-drv-usb-gadget-composite-rename-gadget-serial-consol.patch \
    file://0207-fix-spreadtrum-sprd-bluetooth-broken-park-link-statu.patch \
    file://0208-bluetooth-bcm-Restore-drive_rts_on_open-true-behavio.patch \
    file://0209-Bluetooth-hci_h5-Add-support-for-binding-RTL8723CS-w.patch \
    file://0210-bluetooth-h5-Don-t-re-initialize-rtl8723cs-on-resume.patch \
    file://0211-rtl8703bs-add-chip-type-to-list-and-info-block.patch \
    file://0212-Optimize-TSC2007-touchscreen-add-polling-method.patch \
    file://0213-drv-input-touchscreen-sun4i-ts-Enable-parsing.patch \
    file://0214-input-cyttsp4-Use-i2c-spi-names-directly-in-the-driv.patch \
    file://0215-drv-of-Device-Tree-Overlay-ConfigFS-interface.patch \
    file://0216-Add-ws2812-RGB-driver-for-allwinner-H616.patch \
    file://0217-media-hm5065-Add-subdev-driver-for-Himax-HM5065-came.patch \
    file://0218-media-gc2145-Galaxycore-camera-module-driver.patch \
    file://0219-media-gc2145-Disable-debug-output.patch \
    file://0220-media-gc2145-fix-white-balance-colors.patch \
    file://0221-media-gc2145-Add-PIXEL_RATE-HBLANK-and-VBLANK-contro.patch \
    file://0222-media-gc2145-Added-BGGR-bayer-mode.patch \
    file://0223-media-gc2145-implement-system-suspend.patch \
    file://0224-media-ov5640-Implement-autofocus.patch \
    file://0225-media-ov5640-Improve-firmware-load-time.patch \
    file://0226-media-ov5640-Experiment-Try-to-disable-denoising-sha.patch \
    file://0227-media-ov5640-Fix-focus-commands-blocking-until-compl.patch \
    file://0228-media-ov5640-Don-t-powerup-the-sensor-during-driver-.patch \
    file://0229-media-ov5640-Add-read-only-property-for-vblank.patch \
    file://0230-media-ov5640-Improve-error-reporting.patch \
    file://0231-media-ov5640-Sleep-after-poweroff-to-ensure-next-pow.patch \
    file://0232-media-ov5640-set-default-ae-target-lower.patch \
    file://0233-media-ov5640-use-pm_runtime_force_suspend-resume-for.patch \
    file://0234-usb-typec-anx7688-Add-driver-for-ANX7688-USB-C-HDMI-.patch \
    file://0235-usb-typec-anx7688-I2C-bus-power-needs-to-be-enabled.patch \
    file://0236-tty-serial-8250-dw-Use-fifo-size-from-DTS.patch \
    file://0237-Fix-include-uapi-spi-spidev-module.patch \
    file://0238-drv-spi-spidev-Add-armbian-spi-dev-compatible.patch \
    file://0239-of-property-fw_devlink-Support-allwinner-sram-links.patch \
    file://0240-nfc-pn544-Add-support-for-VBAT-PVDD-regulators.patch \
    file://0241-net-usb-r8152-add-LED-configuration-from-OF.patch \
    file://0242-introduce-uwe5622-driver-for-kernel-6.3.patch \
    file://0243-apply-bugfixes-for-uwe5622-driver.patch \
    file://0244-drivers-uwe5622-fix-compilation-on-6.3-kernels.patch \
    file://0245-fix-driver-for-kernel-6.4.patch \
    file://0246-uwe5622-various-warning-and-firmware-path-fixes.patch \
    file://0247-Add-uwe5622-to-Makefile.patch \
    file://0248-wifi-uwe-fix-uwe5622-tty-sdio.patch \
    file://0249-port-uwe5622-driver-to-kernel-6.1.patch \
    file://0250-wireless-uwe5622-Fix-compilation-with-6.7-kernel.patch \
    file://0251-wireless-uwe5622-reduce-system-load.patch \
    file://0252-wireless-fix-setting-mac-address-for-netdev-in-uwe56.patch \
    file://0253-Fix-makefiles-for-yocto.patch \
    file://0254-Add-sunxi-addr-driver-Used-to-fix-uwe5622-bluetooth-.patch \
    file://0255-wifi-rtw88-8821cu-Fix-firmware-upload-fail.patch \
    file://0256-wifi-rtw88-8821cu-Fix-connection-failure.patch \
    file://0257-wifi-rtw88-8821c-Fix-beacon-loss-and-disconnect.patch \
    file://0258-wifi-rtw88-8821c-Fix-false-alarm-count.patch \
    file://0259-wifi-rtw88-Add-missing-VID-PIDs-doe-8811CU-and-8821C.patch \
    file://0260-mfd-Add-support-for-X-Powers-AC200-EPHY-syscon.patch \
    file://0261-phy-allwinner-sun4i-usb-Add-support-for-usb_role_swi.patch \
    file://0262-drv-phy-sun4i-usb-Allow-reset-line-to-be-shared.patch \
"